### ISSUE TITLE
reoccurring error After closing Chatbook and restarting computer

### ISSUE THREAD

**Issue by MikeGH7** [WolframResearch/Chatbook#665] opened 2024-05-01 06:42 UTC
after restarting PC and opening nonChat notebook, this error popped up again
![Screenshot from 2024-05-01 01-37-45](https://github.com/WolframResearch/Chatbook/assets/16172292/25b096ec-320c-4883-b364-7e4091cce4d7)

The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.4.0"`` |
| ReleaseID | ``"00db891fc2d1dd712145aa46464ded3b71633f75"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.0 for Linux x86 (64-bit) (December 12, 2023)"`` |
| KernelVersion | ``"14.0.0 for Linux x86 (64-bit) (December 13, 2023)"`` |
| SystemID | ``"Linux-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``True`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| InheritanceTest | ``True`` |
| ChatNotebookSettings | ``<\|"InheritanceTest" -> True\|>`` |

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`AttachCodeButtons[Dynamic[FE`attached$$118], CellObject["e3fa04c0-6b3d-43e6-a7ea-820b1060d084", "820ea0e1-4b2c-4542-aa3e-01e4ba38b95c"], "links = Cases[webpage, XMLElement[\"a\", _, _], Infinity];", "Wolfram"]
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "ParentCell", "MessageTemplate" -> "``[``] did not return True.", "MessageParameters" :> {Wolfram`Chatbook`Actions`Private`chatCodeBlockQ, $Failed}, "ConfirmationType" -> "ConfirmBy", "Expression" :> $Failed, "Function" :> Wolfram`Chatbook`Actions`Private`chatCodeBlockQ|>]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$4517
|>
```

</details>

**Comment by rhennigan** [comment] 2024-05-01 20:34
The issue is that the 
```
links = Cases[webpage, XMLElement["a", _, _], Infinity];
```
that you've pasted into the notebook is not plain text--it's a DynamicModule that's expected to be contained in a particular type of inline cell. This can happen if you manually copy content and select the enclosing box structures instead of just the text:

![DynamicModuleSelection](https://github.com/WolframResearch/Chatbook/assets/6674723/1514f075-0bfc-448b-949e-feb7523110f6)

The error message has been fixed in a [more recent release](https://github.com/WolframResearch/Chatbook/releases/tag/v1.4.5), which you can install with:
```
PacletInstall["Wolfram/Chatbook", UpdatePacletSites -> True]
```

Note that this fix doesn't prevent selection of outer box structures, it just avoids issuing that failure message. You'll want to use the provided copy to clipboard button instead of manual selection to avoid this kind of issue in the future.

**Closed by rhennigan** 2024-05-01 20:34 UTC
