### ISSUE TITLE
With long chat sessions, the max message length can be exceeded

### ISSUE THREAD

**Issue by arnoudbuzing** [WolframResearch/Chatbook#2] opened 2023-03-21 17:51 UTC
With long chat sessions, the max message length can be exceeded:

![image](https://user-images.githubusercontent.com/3236874/226697840-37ab2140-7278-4ff3-8476-b1f37fd6b763.png)

**Comment by justanotherlad** [comment] 2023-03-27 12:11
For me, long chat sessions give the following error; not sure how they're related?

![Screenshot from 2023-03-27 17-40-08](https://user-images.githubusercontent.com/31207633/227938063-1c496bf1-49e5-4b05-a33f-fc7b0f8796bd.png)

**Comment by rhennigan** [comment] 2023-07-20 13:34
Closing as duplicate of #76, since that would solve this issue.

**Closed by rhennigan** 2023-07-20 13:34 UTC
