### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by warmersun** [WolframResearch/Chatbook#206] opened 2023-06-28 20:34 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"0.0.30"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Microsoft Windows (64-bit) (June 8, 2023)"`` |
| KernelVersion | ``"13.3.0 for Microsoft Windows (64-bit) (June 8, 2023)"`` |
| SystemID | ``"Windows-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

```
Inherited
```

## Stack Data
```
catchTop
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`PersonaInstaller`Private`scrapeResourceFromShingle["https://www.wolframcloud.com/obj/tamas.simon/DeployedResources/Prompt/AILCETest/"]
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "StatusCode", "MessageTemplate" -> "Assertion `` failed.", "MessageParameters" -> {HoldForm[Wolfram`Chatbook`PersonaInstaller`Private`resp$58943["StatusCode"] === 200]}, "ConfirmationType" -> "ConfirmAssert", "HeldTest" -> Hold[Wolfram`Chatbook`PersonaInstaller`Private`resp$58943["StatusCode"] === 200], "Test" :> False|>]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment] 2023-06-28 20:43
Duplicate of #184

**Closed by rhennigan** 2023-06-28 20:43 UTC
