### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by SGhosal13** [WolframResearch/Chatbook#500] opened 2023-12-26 03:58 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.3.0"`` |
| ReleaseID | ``"e00b6cf8cf704b8be1a076ef98717a70deab7304"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Microsoft Windows (64-bit) (July 24, 2023)"`` |
| KernelVersion | ``"13.3.1 for Microsoft Windows (64-bit) (July 24, 2023)"`` |
| SystemID | ``"Windows-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| StyleSheetVersion | ``"1.3.0.3907219780"`` |

## Stack Data
```
catchTopAs
makeHTTPRequest
constructMessages
cellToString
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Serialization`Private`truncateString[$Failed, 5000]
  "Failure" -> Failure[Wolfram`Chatbook`ErrorUtils`DownValueFallthroughError, <|"Symbol" -> Wolfram`Chatbook`Serialization`Private`truncateString, "ArgumentList" -> HoldComplete[{$Failed, 5000}], "MessageTemplate" -> "Arguments applied to symbol `` did not match any DownValues.", "MessageParameters" -> {HoldForm[Wolfram`Chatbook`Serialization`Private`truncateString]}|>]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$13295
|>
```
![image](https://github.com/WolframResearch/Chatbook/assets/148356627/1b55ddf1-d6b1-4848-98a3-bd23aa2abb4d)

</details>

**Comment by rhennigan** [comment] 2024-01-02 15:10
Duplicate of #499

**Closed by rhennigan** 2024-01-02 15:10 UTC
