### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by spasetto** [WolframResearch/Chatbook#320] opened 2023-08-11 01:40 UTC
It does not work.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.1.1"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.2 for Microsoft Windows (64-bit) (November 18, 2022)"`` |
| KernelVersion | ``"13.2.0 for Microsoft Windows (64-bit) (November 18, 2022)"`` |
| SystemID | ``"Windows-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |

## Stack Data
```
catchTop
checkResponse
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`toolFreeQ[ProgressIndicator[Appearance -> "Percolate"]]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment] 2023-08-11 20:33
Duplicate of #296

**Closed by rhennigan** 2023-08-11 20:33 UTC
