### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by Jesse233-333** [WolframResearch/Chatbook#758] opened 2024-08-15 01:51 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.4.0"`` |
| ReleaseID | ``"00db891fc2d1dd712145aa46464ded3b71633f75"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.0 for Microsoft Windows (64-bit) (2023å¹´12æ12æ¥)"`` |
| KernelVersion | ``"14.0.0 for Microsoft Windows (64-bit) (December 13, 2023)"`` |
| SystemID | ``"Windows-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| StyleSheetVersion | ``"1.4.0.3913547000"`` |

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`EvaluateChatInput[CellObject["137bc08c-8017-3f42-b2e1-2689427ac018", "05a59060-4373-7347-8efc-64443eabdb6f"], NotebookObject["71ad5d9b-f118-9a4f-9c6c-c7bae5bf9e07", "6d155112-2bba-ba47-846b-538510796de2"], Wolfram`Chatbook`Settings`currentChatSettings[NotebookObject["71ad5d9b-f118-9a4f-9c6c-c7bae5bf9e07", "6d155112-2bba-ba47-846b-538510796de2"]]]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$34562
|>
```

</details>

**Comment by rhennigan** [comment] 2024-08-21 20:17
This should be fixed since version 1.4.5. Please reopen if you can reproduce the issue in 1.5.0 or later.

**Closed by rhennigan** 2024-08-21 20:17 UTC
