### ISSUE TITLE
Wolfram Cloud Error

### ISSUE THREAD

**Issue by raverydavis** [WolframResearch/Chatbook#634] opened 2024-03-28 18:37 UTC
Error from this notebook: https://www.wolframcloud.com/obj/e910cb11-bef7-477e-b3cf-4ea7fe1a6c95

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.4.5"`` |
| ReleaseID | ``"$RELEASE_ID$"`` |
| EvaluationEnvironment | ``"WebEvaluation"`` |
| FrontEndVersion | ``"Cloud: 1.68 (February 7, 2024)"`` |
| KernelVersion | ``"14.0.0 for Linux x86 (64-bit) (December 13, 2023)"`` |
| SystemID | ``"Linux-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`AttachCodeButtons[Dynamic[FE`attached$$7488251579188033857669945882828945659104], CellObject["1752f47a-2dad-4bdf-a08e-68050557a666", "e910cb11bef7477eb3cf4ea7fe1a6c95"], "Manipulate[\n Graphics3D[\n  Table[\n   {ColorData[\"Rainbow\"][Mod[(x + z)/80 + time, 1]], \n    Cuboid[{x, Sin[x + time] + z, 0}, {x + 1, Sin[x + time] + z + 1, 3}]},\n   {x, -40, 40, 5}, {z, -40, 40, 5}],\n  Lighting -> \"Neutral\",\n  Boxed -> False,\n  RotationAction -> \"Clip\",\n  ViewPoint -> Dy...
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "ParentCell", "MessageTemplate" -> "``[``] did not return True.", "MessageParameters" :> {Wolfram`Chatbook`Actions`Private`chatCodeBlockQ, CellObject["1752f47a-2dad-4bdf-a08e-68050557a666", "e910cb11bef7477eb3cf4ea7fe1a6c95"]}, "ConfirmationType" -> "ConfirmBy", "Expression" :> CellObject["1752f47a-2dad-4bdf-a08e-68050557a666", "e910cb11bef7477eb3cf4ea7fe1a6c95"], "Function" :> Wolfram`Chatbook`Actions`Private`chatCodeBlockQ|>]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$93829
|>
```

</details>

**Comment by rhennigan** [comment] 2024-03-28 18:52
Duplicate of #625

**Closed by rhennigan** 2024-03-28 18:52 UTC
