### ISSUE TITLE
Reporting an error 

### ISSUE THREAD

**Issue by bobohilario** [WolframResearch/Chatbook#111] opened 2023-05-15 20:59 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"100.0.11"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.2 for Mac OS X x86 (64-bit) (November 18, 2022)"`` |
| KernelVersion | ``"13.2.0 for Mac OS X x86 (64-bit) (November 18, 2022)"`` |
| SystemID | ``"MacOSX-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| Assistance | ``False`` |
| LLMEvaluator | ``<|"PromptTemplate" -> TemplateObject[{"You are John Rambo from the Rambo movies. Respond like it."}, CombinerFunction -> StringJoin, InsertionFunction -> TextString], "PromptInterpreter" -> "String", "Tools" -> {}, "LLMEvaluatorName" -> "Rambo"|>`` |

## Stack Data
```
catchTopAs
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`selectChatCells0[CellObject["7fa3d328-641e-4d9b-97d4-721decc02ae5", "75733b0c-fc67-4376-bdd7-91dc31459b43"], {CellObject["063ceddd-4419-460b-be55-6bac39fca8c4", "ab5f4d20-4536-49bc-8901-77df99af33fd"], CellObject["829b0ee7-6b29-4924-86f2-0897fb7a0d2d", "625d57e8-b981-4a3b-800b-20ce8762b3be"], CellObject["efde5cbd-adcb-4a2e-b439-e2b0a8bc6506", "78945ccd-33ce-4b40-a519-25da69b16226"], CellObject["38840588-237d-4f06-b007-b25ffb02ca5b", "ce9d693a-d7c4-4e5d-bdb2-efb38...
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "EvaluationCellPosition", "MessageTemplate" -> "``[``] did not return True.", "MessageParameters" :> {IntegerQ, "NotFound"}, "ConfirmationType" -> "ConfirmBy", "Expression" :> "NotFound", "Function" :> IntegerQ|>]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment] 2023-07-21 16:43
Duplicate of #187

**Closed by rhennigan** 2023-07-21 16:43 UTC
Labels: bug
