### ISSUE TITLE
EvaluationCell[] found the docked cell

### ISSUE THREAD

**Issue by bobohilario** [WolframResearch/Chatbook#118] opened 2023-05-17 14:58 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"0.0.11.4"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.2 for Mac OS X x86 (64-bit) (November 18, 2022)"`` |
| KernelVersion | ``"13.2.0 for Mac OS X x86 (64-bit) (November 18, 2022)"`` |
| SystemID | ``"MacOSX-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| Assistance | ``False`` |
| LLMEvaluator | ``"RitzyMitzi"`` |

## Stack Data
```
catchTopAs
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`selectChatCells0[CellObject["d755aebf-8371-427a-bedf-c7848c0745f9", "47c1dc9c-d60f-463c-aba4-d2c47c64fad3"], {CellObject["1dab589a-c155-4a38-a131-a8f3dfcb1dee", "1430c517-1671-4bff-a010-60329d44d5ec"], CellObject["e83e8afd-4745-4ae8-b416-add2052b7fa2", "0f3bdd72-c3ee-4b4c-82f9-880bdf371199"], CellObject["65e38314-43a1-4e9f-b1df-48096eed771d", "2bc59b28-6573-4eed-b494-f963efb13b89"], CellObject["9a4f2279-3230-4d2b-afdc-e8fe419f2d9f", "4598cf5a-4693-4b92-bca0-6ef09...
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "EvaluationCellPosition", "MessageTemplate" -> "``[``] did not return True.", "MessageParameters" :> {IntegerQ, "NotFound"}, "ConfirmationType" -> "ConfirmBy", "Expression" :> "NotFound", "Function" :> IntegerQ|>]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment] 2023-07-17 21:41
Duplicate of #187

**Closed by rhennigan** 2023-07-17 21:41 UTC
Labels: bug
