### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by larrybloxham** [WolframResearch/Chatbook#656] opened 2024-04-19 20:11 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.4.0"`` |
| ReleaseID | ``"00db891fc2d1dd712145aa46464ded3b71633f75"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.0 for Mac OS X x86 (64-bit) (December 12, 2023)"`` |
| KernelVersion | ``"14.0.0 for Mac OS X x86 (64-bit) (December 13, 2023)"`` |
| SystemID | ``"MacOSX-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| StyleSheetVersion | ``"1.4.0.3913547000"`` |

## Stack Data
```
catchTopAs
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`SendChat`Private`prepareChatOutputPage[CellObject["a1f582f7-a0e2-436b-aab2-95fde84754d2", "58db2089-355f-43bb-8c3f-94d6f1afde3e"], Cell[BoxData[TagBox[DynamicBox[ToBoxes[Wolfram`Chatbook`SendChat`Private`$dynamicTrigger; Wolfram`Chatbook`Common`catchTop[Wolfram`Chatbook`SendChat`Private`dynamicTextDisplay[Wolfram`Chatbook`SendChat`Private`container$30350, (Wolfram`Chatbook`$ChatHandlerData["EventName"] = "FormatChatOutput"; Wolfram`Chatbook`FormatChatOutput[##1]) & , True]], Sta...
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "NotebookRead", "MessageTemplate" -> "`` does not match ``.", "MessageParameters" :> {$Failed, _Cell}, "ConfirmationType" -> "ConfirmMatch", "Expression" :> $Failed, "Pattern" :> _Cell|>]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$30520
|>
```

</details>

**Comment by rhennigan** [comment] 2024-05-01 20:46
This was fixed in 1.4.2. You can get the latest version by evaluating the following:
```
PacletInstall["Wolfram/Chatbook", UpdatePacletSites -> True]
```

(Duplicate of #572)

**Closed by rhennigan** 2024-05-01 20:46 UTC
