### ISSUE TITLE
"An unexpected error occurred"

### ISSUE THREAD

**Issue by piquan** [WolframResearch/Chatbook#307] opened 2023-07-28 23:55 UTC
Not a recurring problem for me; just reporting the bug to give you data.

I was opening looking at prompts.  I'd just evaluated `LLMPrompt["KnowAboutMe"]`, and after the resource was fetched, the resulting TemplateObject appeared in the Out[2] field.  I clicked on the + icon to display the content, and that's when the error came up.  There was very little time between these events; I suppose I may have misclicked something, but can't imagine what.

The error said it happened during evaluation of In[3], which I hadn't entered yet.  (I'd only entered `LLMPrompt["HaikuStyled"]` and `LLMPrompt["KnowAboutMe"]` so far.)

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.0.0"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Linux x86 (64-bit) (June 3, 2023)"`` |
| KernelVersion | ``"13.3.0 for Linux x86 (64-bit) (June 3, 2023)"`` |
| SystemID | ``"Linux-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

```
Inherited
```

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`writeChunk[Dynamic[Wolfram`Chatbook`Actions`Private`container$14877], CellObject["29ae40d0-14a9-482d-ae1a-ce25f8e4ae73", "068ff4a8-f6ca-4437-bcbe-b0a4edb6937f"], ",\"finish_reason\":null}]}\n\n"]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment] 2023-07-29 13:15
Duplicate of #210

**Closed by rhennigan** 2023-07-29 13:15 UTC
