### ISSUE TITLE
refuses to do more than one cell 

### ISSUE THREAD

**Issue by walkerjian** [WolframResearch/Chatbook#325] opened 2023-08-18 06:40 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.0.0"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.2 for Mac OS X x86 (64-bit) (January 30, 2023)"`` |
| KernelVersion | ``"13.2.1 for Mac OS X x86 (64-bit) (January 27, 2023)"`` |
| SystemID | ``"MacOSX-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| ChatDrivenNotebook | ``True`` |
| LLMEvaluator | ``"PlainChat"`` |

## Stack Data
```
EvaluateChatInput
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`FrontEnd`rootEvaluationCell[CellObject["2df6481a-4f3b-480a-b7a7-159a11c25558", "a99c73ce-3908-4c3e-920a-bf6f92c8a822"], $Failed]
  "Arguments" -> {}
|>
```

</details>

**Comment by walkerjian** [comment] 2023-08-18 06:42
Failure["Chatbook::Internal", <|"MessageParameters" :> {
Hyperlink[
    "Report this issue »", 
     "https://github.com/WolframResearch/Chatbook/issues/new?title=\
Insert+Title+Here&labels=bug&body=Describe+the+issue+in+detail+here.+\
Attach+any+relevant+screenshots+or+files.+The+section+below+was+\
automatically+generated.+Remove+any+information+that+you+do+not+wish+\
to+include+in+the+report.%0A%0A%3Cdetails%3E%0A%3Csummary%3EDebug+\
Data%3C%2Fsummary%3E%0A%0A%7C+Property+%7C+Value+%7C%0A%7C+---+%7C+---\
+%7C%0A%7C+Name+%7C+%60%60%22Wolfram%2FChatbook%22%60%60+%7C%0A%7C+\
Version+%7C+%60%60%221.0.0%22%60%60+%7C%0A%7C+EvaluationEnvironment+%\
7C+%60%60%22Session%22%60%60+%7C%0A%7C+FrontEndVersion+%7C+%60%60%\
22Desktop%3A+13.2+for+Mac+OS+X+x86+%2864-bit%29+%28January+30%2C+2023%\
29%22%60%60+%7C%0A%7C+KernelVersion+%7C+%60%60%2213.2.1+for+Mac+OS+X+\
x86+%2864-bit%29+%28January+27%2C+2023%29%22%60%60+%7C%0A%7C+SystemID+\
%7C+%60%60%22MacOSX-x86-64%22%60%60+%7C%0A%7C+Notebooks+%7C+%60%\
60True%60%60+%7C%0A%7C+DynamicEvaluation+%7C+%60%60False%60%60+%7C%0A%\
7C+SynchronousEvaluation+%7C+%60%60False%60%60+%7C%0A%7C+\
TaskEvaluation+%7C+%60%60False%60%60+%7C%0A%0A%23%23+Settings%0A%0A%\
7C+Property+%7C+Value+%7C%0A%7C+---+%7C+---+%7C%0A%7C+\
ChatDrivenNotebook+%7C+%60%60True%60%60+%7C%0A%7C+LLMEvaluator+%7C+%\
60%60%22PlainChat%22%60%60+%7C%0A%0A%23%23+Stack+Data%0A%60%60%60%\
0AEvaluateChatInput%0AthrowFailure%0AtrimURL%0A%60%60%60%0A%0A%23%23+\
Failure+Data%0A%0A%60%60%60%0A%3C%7C%0A++%22Evaluation%22+%3A%3E+\
Wolfram%60Chatbook%60FrontEnd%60rootEvaluationCell%5BCellObject%5B%\
222df6481a-4f3b-480a-b7a7-159a11c25558%22%2C+%22a99c73ce-3908-4c3e-\
920a-bf6f92c8a822%22%5D%2C+%24Failed%5D%0A++%22Arguments%22+-%3E+%7B%\
7D%0A%7C%3E%0A%60%60%60%0A%0A%0A%3C%2Fdetails%3E"], <|
    "Evaluation" :> Wolfram`Chatbook`FrontEnd`rootEvaluationCell[
CellObject[
       "2df6481a-4f3b-480a-b7a7-159a11c25558", 
        "a99c73ce-3908-4c3e-920a-bf6f92c8a822"], $Failed], 
     "Arguments" -> {}|>}, "MessageTemplate" :> 
  MessageName[Wolfram`Chatbook`Chatbook, "Internal"]|>]
<img width="1431" alt="Screenshot 2023-08-18 at 4 40 47 pm" src="https://github.com/WolframResearch/Chatbook/assets/2534494/ed373a34-ec17-4eb8-95fb-9a56667c8fc4">

**Comment by raverydavis** [comment] 2023-08-18 17:02
Hi, can you run PacletFind["*Chatbook*"] and let us know what Paclets it says are installed?

**Comment by walkerjian** [comment] 2023-08-18 21:19
I managed to partially fix it by starting each chat cell with a ‘
I will continue my explorations and get back to you

**Comment by rhennigan** [comment] 2023-08-24 12:14
Duplicate of #187

**Closed by rhennigan** 2023-08-24 12:14 UTC
