### ISSUE TITLE
Mathematica 13.3 Chat-Driven Notebook Error Message

### ISSUE THREAD

**Issue by sl1685** [WolframResearch/Chatbook#253] opened 2023-07-19 01:52 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.0.2"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Microsoft Windows (64-bit) (June 3, 2023)"`` |
| KernelVersion | ``"13.3.0 for Microsoft Windows (64-bit) (June 3, 2023)"`` |
| SystemID | ``"Windows-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``True`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| ChatDrivenNotebook | ``True`` |
| LLMEvaluator | ``"PlainChat"`` |

## Stack Data
```
catchTopAs
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`FrontEnd`currentChatSettings[CellObject["60403758-a7c9-40bc-81b6-4280cca1c077", "267146d7-545a-4e61-8482-6822a947f94c"], "LLMEvaluator"]
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "ChatCells", "MessageTemplate" -> "`` does not match ``.", "MessageParameters" :> {{}, {__CellObject}}, "ConfirmationType" -> "ConfirmMatch", "Expression" :> {}, "Pattern" :> {__CellObject}|>]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment] 2023-07-19 18:57
Duplicate of #254

**Closed by rhennigan** 2023-07-19 18:57 UTC
