### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by guohongnz** [WolframResearch/Chatbook#225] opened 2023-07-07 00:25 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"0.0.29"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Cloud: 1.66 (June 16, 2023)"`` |
| KernelVersion | ``"13.3.0 for Linux x86 (64-bit) (June 3, 2023)"`` |
| SystemID | ``"Linux-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``True`` |
| TaskEvaluation | ``False`` |

## Settings

```
Inherited
```

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`StopChat[Wolfram`Chatbook`Actions`Private`cell]
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "Container", "MessageTemplate" -> "``[``] did not return True.", "MessageParameters" :> {StringQ, ProgressIndicator[Appearance -> "Percolate"]}, "ConfirmationType" -> "ConfirmBy", "Expression" :> ProgressIndicator[Appearance -> "Percolate"], "Function" :> StringQ|>]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment] 2023-07-17 21:34
Duplicate of #86

**Closed by rhennigan** 2023-07-17 21:34 UTC
