### ISSUE TITLE
Mathemeatica Issue

### ISSUE THREAD

**Issue by juliastein561** [WolframResearch/Chatbook#370] opened 2023-09-24 15:55 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.0.4"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Mac OS X ARM (64-bit) (July 24, 2023)"`` |
| KernelVersion | ``"13.3.1 for Mac OS X ARM (64-bit) (July 24, 2023)"`` |
| SystemID | ``"MacOSX-ARM64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

```
Inherited
```

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`ExplodeInPlace[CellObject["d6c985da-24aa-496a-a3f4-a5ef846f14b7", "e6ce8967-c5d2-4703-87d2-fa5cc73f59f8"]]
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "ExplodeCell", "MessageTemplate" -> "`` does not match ``.", "MessageParameters" :> {{}, {__Cell}}, "ConfirmationType" -> "ConfirmMatch", "Expression" :> {}, "Pattern" :> {__Cell}|>]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment] 2023-09-26 14:26
Duplicate of #369

**Closed by rhennigan** 2023-09-26 14:26 UTC
