### ISSUE TITLE
Unknown Issue with Chat enabled Notebook

### ISSUE THREAD

**Issue by Tetesept500** [WolframResearch/Chatbook#639] opened 2024-04-10 11:19 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.4.0"`` |
| ReleaseID | ``"00db891fc2d1dd712145aa46464ded3b71633f75"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.0 for Microsoft Windows (64-bit) (December 12, 2023)"`` |
| KernelVersion | ``"14.0.0 for Microsoft Windows (64-bit) (December 13, 2023)"`` |
| SystemID | ``"Windows-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``True`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| StyleSheetVersion | ``"1.4.0.3913547000"`` |

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`AttachCodeButtons[Dynamic[FE`attached$$1273], CellObject["54266705-2e1e-5d4e-9344-d7dc125240e5", "5ddc0cb5-e7c4-ef4c-9bf3-9592a0595e74"], "header = First[myData];\ndata = Rest[myData];\nresults = data[[All, 1]];\nfactors = data[[All, 2 ;;]];", "Wolfram"]
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "ParentCell", "MessageTemplate" -> "``[``] did not return True.", "MessageParameters" :> {Wolfram`Chatbook`Actions`Private`chatCodeBlockQ, $Failed}, "ConfirmationType" -> "ConfirmBy", "Expression" :> $Failed, "Function" :> Wolfram`Chatbook`Actions`Private`chatCodeBlockQ|>]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$470396
|>
```

</details>

**Comment by rhennigan** [comment] 2024-04-10 13:26
Duplicate of #630

**Closed by rhennigan** 2024-04-10 13:26 UTC
