### ISSUE TITLE
Error using \ inside a code cell

### ISSUE THREAD

**Issue by raverydavis** [WolframResearch/Chatbook#605] opened 2024-02-23 17:49 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.4.0"`` |
| ReleaseID | ``"00db891fc2d1dd712145aa46464ded3b71633f75"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.0 for Mac OS X ARM (64-bit) (December 16, 2023)"`` |
| KernelVersion | ``"14.0.0 for Mac OS X ARM (64-bit) (December 13, 2023)"`` |
| SystemID | ``"MacOSX-ARM64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``True`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| StyleSheetVersion | ``"1.4.0.3913547000"`` |

## Stack Data
```
insertInlineReference
loadDefinitionNotebook
ensureChatInputCell
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`FrontEnd`rootEvaluationCell[CellObject["5cfd8e4c-28ce-4d5b-9003-ac137b5c33e6", "1f5e46dd-262e-4cdb-bec7-9d8021697b19"], {CellObject["3e2b84b0-9813-4727-8a04-733199ebe40f", "6419c708-c7bf-434c-9e2e-85d5a044354f"]}]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$4637
|>
```

</details>

**Comment by rhennigan** [comment] 2024-03-07 14:12
Duplicate of #566

**Closed by rhennigan** 2024-03-07 14:12 UTC
