### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by guraltsev** [WolframResearch/Chatbook#856] opened 2024-10-25 14:16 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

https://github.com/WolframResearch/Chatbook/blob/f6143fb833bd66de9b3d322fa4de64b6787871ca/Source/Chatbook/ChatMessages.wl#L486-L486

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.5.0"`` |
| ReleaseID | ``"f6143fb833bd66de9b3d322fa4de64b6787871ca"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Microsoft Windows (64-bit) (July 24, 2023)"`` |
| KernelVersion | ``"13.3.1 for Microsoft Windows (64-bit) (July 24, 2023)"`` |
| SystemID | ``"Windows-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| PersonaFavorites | ``{"CodeAssistant", "CodeWriter", "PlainChat"}`` |
| InheritanceTest | ``True`` |
| VisiblePersonas | ``{"CodeAssistant", "CodeWriter", "PlainChat", "RawModel"}`` |
| ServiceDefaultModel | ``<\|"OpenAI" -> "gpt-4o"\|>`` |
| Model | ``<\|"Service" -> "OpenAI", "Name" -> "gpt-4-turbo"\|>`` |
| Assistance | ``True`` |
| CurrentPreferencesTab | ``"Services"`` |
| LLMEvaluator | ``"CodeWriter"`` |
| StyleSheetVersion | ``"1.5.0.3931772186"`` |

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`ChatMessages`Private`tokenCount[<|"Assistance" -> True, "Authentication" -> Automatic, "AutoFormat" -> True, "BasePrompt" -> {"WolframLanguageStyle"}, "BypassResponseChecking" -> False, "ChatContextPreprompt" -> Automatic, "ChatDrivenNotebook" -> False, "ChatHistoryLength" -> 1000, "ChatInputIndicator" -> "💬", "ConversionRules" -> None, "CurrentPreferencesTab" -> "Services", "Description" -> "AI code generation with minimal commentary", "DisplayName" -> RawBoxes[DynamicBox[FEPri...
  "Information" -> "TokenCount@@Source/Chatbook/ChatMessages.wl:486,18-486,91"
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "TokenCount@@Source/Chatbook/ChatMessages.wl:486,18-486,91", "MessageTemplate" -> "`` does not match ``.", "MessageParameters" :> {Wolfram`Chatbook`C
```

</details>

**Comment by rhennigan** [comment] 2024-11-01 13:41
Duplicate of #857

**Closed by rhennigan** 2024-11-01 13:41 UTC
