### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by kmaclaury** [WolframResearch/Chatbook#197] opened 2023-06-26 22:39 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"0.0.30"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.2 for Mac OS X ARM (64-bit) (November 19, 2022)"`` |
| KernelVersion | ``"13.2.0 for Mac OS X ARM (64-bit) (November 18, 2022)"`` |
| SystemID | ``"MacOSX-ARM64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| TemperatureSetting | ``0.8`` |
| Model | ``"gpt-3.5-turbo"`` |
| Temperature | ``0.8`` |
| LLMEvaluator | ``"CodeAssistant"`` |

## Stack Data
```
catchTopAs
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`prepareChatOutputPage[CellObject["a2ac05d7-919a-4ecb-9659-4d2c1bb31b9d", "4207ed94-62fb-4907-9466-75e2270c6404"], Cell[BoxData[DynamicBox[ToBoxes[Refresh[Wolfram`Chatbook`Actions`Private`dynamicTextDisplay[Wolfram`Chatbook`Actions`Private`container$29943, True], TrackedSymbols :> {}, UpdateInterval -> 0.4], StandardForm], Initialization :> If[$SessionID =!= 29703138794319631912, NotebookDelete[EvaluationCell[]]], Deinitialization :> Quiet[TaskRemove[Wolfram`Chatb...
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "NotebookRead", "MessageTemplate" -> "`` does not match ``.", "MessageParameters" :> {$Failed, _Cell}, "ConfirmationType" -> "ConfirmMatch", "Expression" :> $Failed, "Pattern" :> _Cell|>]
  "Arguments" -> {}
|>
```

</details>

**Comment by kmaclaury** [comment] 2023-06-26 22:47
Apologies, I hadn't updated my paclet.  The most recent version doesn't do this.

**Comment by rhennigan** [comment] 2023-06-27 20:24
Duplicate of #187

**Closed by rhennigan** 2023-06-27 20:24 UTC
Labels: duplicate
