### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by koutsoyiannis** [WolframResearch/Chatbook#224] opened 2023-07-05 18:23 UTC
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.0.1"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.2 for Microsoft Windows (64-bit) (January 30, 2023)"`` |
| KernelVersion | ``"13.2.1 for Microsoft Windows (64-bit) (January 27, 2023)"`` |
| SystemID | ``"Windows-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| ChatDrivenNotebook | ``True`` |
| LLMEvaluator | ``"PlainChat"`` |

## Stack Data
```
EvaluateChatInput
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`FrontEnd`rootEvaluationCell[CellObject["61a32f62-aa49-42bd-ab68-53ed930b2e85", "367f444e-e87b-47cf-86ef-c88a09fb0c67"], $Failed]
  "Arguments" -> {}
|>
```

</details>

**Comment by koutsoyiannis** [comment] 2023-07-05 18:25
I have struggled for days to connect to chat from mathematica (I upgraded to version 13.2) with no success. Could you help me?

**Comment by raverydavis** [comment] 2023-07-11 13:34
> I have struggled for days to connect to chat from mathematica (I upgraded to version 13.2) with no success. Could you help me?

Is there more information you can provide? You need a valid API key from OpenAI

**Comment by rhennigan** [comment] 2023-07-17 21:37
The failure data above indicates that this is a duplicate of #187

**Closed by rhennigan** 2023-07-17 21:37 UTC
